HMIProject/open62541-sys

CHANGELOG.md
build.rs

This uses parse callbacks to adjust the name of `UA_EMPTY_ARRAY_SENTINEL` back to its proper name without trailing underscore.
The reason we had an underscore in the first place was that we needed (and still need) to define a static constant to let bindgen define what in the original code is a non-trivial macro.

Use original name for `UA_EMPTY_ARRAY_SENTINEL` export

---

CHANGELOG.md
build.rs
wrapper.h

For HMIProject/open62541#22 we need to pass back control to C string formatting with `vprintf` et al. For this, we include the bounds-checked string variant `vsnprintf()` in the generated bindings. It is available via `<stdio.h>` anyway and does not increase the size of the resulting library.

Add binding of `vsnprintf()` to use for formatting log messages

---

CHANGELOG.md
build.rs
tests/integration_test.rs
wrapper.c
wrapper.h

This adds a custom wrapper to export `vsnprintf()` on Windows systems with C libraries older than the UCRT introduced in Visual Studio 2015 and Windows 10. On these systems, `vsnprintf()` is only available as `_vsnprintf()` and with a different runtime behavior.

Add wrapper for `vsnprintf()` on Windows

---

build.rs
tests/integration_test.rs
wrapper.c
wrapper.h

This adds back the logic regarding the use of `RS_` prefixes to whitelist custom exported items. It also adds back the tests that check that our custom exports still appear in the generated bindings (even though they are treated as internal).

Add back export logic of wrapper items

---

tests/integration_test.rs
wrapper.c
wrapper.h

This fixes a regression in #12 where we lost access to our wrapper for `UA_EMPTY_ARRAY_SENTINEL`.

Fix export of `UA_EMPTY_ARRAY_SENTINEL` constant

---

.github/workflows/latest-dependencies.yaml
.github/workflows/test.yaml
Cargo.toml

This adds the same build targets for verifying builds on different platforms that were added in https://github.com/HMIProject/open62541/pull/33. For the linux-musl build, we have to upgrade the MSRV to 1.72.

GitHub CI: Use same build targets as in open62541 crate

---

Cargo.toml
build.rs

This adjusts the comments regarding the Rust version used when invoking `bindgen` in `build.rs`. The version there should be more or less kept in sync with the MSRV in `Cargo.toml`.
We say "more or less" because bindgen does only track Rust versions that affect the ABI. When we have an MSRV that had no ABI changes, we leave the version in `build.rs` unchanged at the previous version (we must not use any newer version).

Add note regarding `build.rs` to MSRV in `Cargo.toml`

---

.github/workflows/latest-dependencies.yaml
.github/workflows/test.yaml
build.rs

This is a work-around to temporarily enable [musl libc](https://www.musl-libc.org) builds again. It is not ideal because we manually add include paths to Linux headers from the build system's environment which have been deliberately omitted from the musl include directory.
The musl FAQs [warn against the use of kernel headers](https://wiki.musl-libc.org/faq#Q:-Why-am-I-getting-), so we will likely keep this work-around only until open62541 allows building without features that require those headers, at least when targeting musl environments.
See https://github.com/open62541/open62541/issues/6360

Explicitly include Linux headers to re-enable musl build

---

CHANGELOG.md

This upgrades the contained source of open62541 to the released version [1.4.0](https://github.com/open62541/open62541/releases/tag/v1.4.0).

Upgrade open62541 to released version 1.4.0

---

CHANGELOG.md

This upgrades the bundled dependency on open62541 to the latest released version [1.4.3](https://github.com/open62541/open62541/releases/tag/v1.4.3).

Upgrade to open62541 version 1.4.3

---

CHANGELOG.md

This upgrades the bundled dependency on open62541 to the latest released version [1.4.4](https://github.com/open62541/open62541/releases/tag/v1.4.4).

Upgrade to open62541 version 1.4.4

---

Cargo.lock
Cargo.toml
build.rs

This replaces the declaration of `extern "C"` blocks with `unsafe extern "C"` as will be required by Rust 2024. Remove this when https://github.com/rust-lang/rust-bindgen/issues/2901 is merged and [bindgen](https://crates.io/crates/bindgen) can generate these blocks automatically as required.

Add unsafe to extern blocks for Rust 2024

---

.markdownlint-cli2.yaml
.pre-commit-config.yaml
Cargo.toml

This updates the [pre-commit](https://pre-commit.com) repos and makes sure to use the proper (non-deprecated) name for the Markdown config. It also adds checks for TOML formatting.

Update pre-commit config and hooks

---

.gitmodules
CHANGELOG.md
Cargo.toml
build.rs

This adds a feature flag `mbedtls` that builds open62541 with [Mbed TLS](https://www.trustedfirmware.org/projects/mbed-tls/) support for encryption. We bundle the Mbed TLS sources alongside the sources of open62541 to support all existing build targets.

Add feature flag for enabling Mbed TLS support

---

wrapper.h

This is a follow-up to #39 and includes additional bindings, some of which are only available with feature flag `mbedtls`.

Include open62541 headers required for encryption

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This upgrades our build dependency [bindgen](https://crates.io/crates/bindgen) from version 0.69.x to 0.70.x. The generated `bindings.rs` does not seem to change apart from the compile time tests adjusted in https://github.com/rust-lang/rust-bindgen/pull/2787.t

Upgrade to latest bindgen version for building

---

CHANGELOG.md

This upgrades the bundled dependency on open62541 to the latest released version [1.4.8](https://github.com/open62541/open62541/releases/tag/v1.4.8).

Upgrade to open62541 version 1.4.8

---

CHANGELOG.md
wrapper.h

This is a follow-up to #43 where support for creating certificates with Mbed TLS was [added](https://github.com/open62541/open62541/pull/6145).[^1] We include the bindings now as well to facilitate certificate creation.
[^1]: Until then, `UA_CreateCertificate()` was only available with OpenSSL.

Include headers for certificate creation in bindings

---

CHANGELOG.md

This upgrades the bundled dependency on Mbed TLS to the latest released version [3.6.3](https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.3).

Upgrade to Mbed TLS version 3.6.3

---

build.rs

For cross-compilation, the [`cross`](https://github.com/cross-rs/cross/) tool is commonly used.
However, `cross` sets the following CMake flags during cross-compilation (ref: https://github.com/cross-rs/cross/issues/1291 , https://github.com/cross-rs/cross/issues/1270 , https://github.com/cross-rs/cross/issues/1180 ):
```
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
As a result, when using  `MBEDTLS_FOLDER_*` variables, [`find_library`](https://github.com/open62541/open62541/blob/55d0b902f7a2bbe7fc40748fa312c092f1ead649/tools/cmake/FindMbedTLS.cmake#L17-L19) and `find_include` may fail because it searches under `${CMAKE_FIND_ROOT_PATH}/${MBEDTLS_FOLDER_*}` (e.g., …

Resolve MBEDTLS library path issues when cross-compiling with `cross`
